### ISSUE TITLE
Add support for multiple Windows SDK versions

### ISSUE THREAD

**Issue by kdewald** [OpenBluetoothToolbox/SimpleBLE#54]
Right now everything only works with `10.0.19041.0`. Newer versions throw this error:

```
SimpleBLE\src\windows\Utils.cpp(14,5): error C3861: 'WINRT_CoGetApartmentType': identifier not found 
\SimpleBLE\src\windows\Utils.cpp(19,39): error C3861: 'WINRT_RoInitialize': identifier not found 
```

Andrej already gave the solution in https://github.com/OpenBluetoothToolbox/SimpleBLE/pull/39, we just need to finish the implementation.

**Comment by kdewald** [comment]
Will be part of the v0.4.0 release.
